version: "3.4"
services:
  dty_backend:
    container_name: dty_backend
    image: node:18
    depends_on:
      - database
    working_dir: /var/www/html/app
    entrypoint: /bin/bash -c "npm run start:dev"
    ports:
      - "8000:80"
    volumes:
      - ./backend/:/var/www/html/app
    tty: true
  dty_frontend:
    container_name: dty_frontend
    image: node:18
    working_dir: /var/www/html/app
    entrypoint: /bin/bash -c "npm run dev"
    ports:
      - "80:80"
    volumes:
      - ./frontend/:/var/www/html/app
    tty: true
  database:
    container_name: dty_database
    image: postgres:15.2
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
